Repository palexdev/MaterialFX, pull requests merged in 2023-01, with the labels that each got.

#205 Using cell factory from combobox when initializing popup content in f…
  materialfx/src/main/java/io/github/palexdev/materialfx/skins/MFXFilterComboBoxSkin.java
Labels: enhancement

#253 Adding czech language translation.
  materialfx/src/main/java/io/github/palexdev/materialfx/i18n/Language.java
  materialfx/src/main/resources/io/github/palexdev/materialfx/i18n/mfxlang_cs_CZ.properties
Labels: roadmap

#262 Fix for #261 - FilterPaneSkin creates MFXComboBox's cells with hardco…
  materialfx/src/main/java/io/github/palexdev/materialfx/skins/MFXFilterPaneSkin.java
  materialfx/src/main/resources/io/github/palexdev/materialfx/css/MFXFilterPane.css
Labels: enhancement, roadmap

#212 Fix for issue #210 Possible memory leak
  materialfx/src/main/java/io/github/palexdev/materialfx/utils/others/observables/OnChanged.java
  materialfx/src/main/java/io/github/palexdev/materialfx/utils/others/observables/OnInvalidated.java
  materialfx/src/main/java/io/github/palexdev/materialfx/utils/others/observables/When.java
Labels: enhancement
